### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by FatimahD-Alotaibi** [dki-lab/Freebase-Setup#11]
Hi. Thank you so much for sharing the code.
I followed the instruction in the readme to start Virtuoso service. However, when I run the python3 fix_freebase_literal_format.py
It gives me this error.
    subj, pred, obj, rest = line.split("\t")
TypeError: a bytes-like object is required, not 'str'

could you please help?

**Comment by ysu1989** [comment]
are you using the provided virtuoso db files (downloaded via a Dropbox link)? If so, you don't need to run the `fix_freebase_literal_format.py` at all

**Comment by FatimahD-Alotaibi** [comment]
Thank you so much... skipped that.
However, when I run this 
python3 virtuoso.py start 3001 -d virtuoso_db

it keeps giving me this message 
The VDBMS server process terminated prematurely
after opening the database. 
Any suggestion?

**Comment by FatimahD-Alotaibi** [comment]
Thank you I skipped that. However, when I try to run the SPARQL query, the Sparql editor returns nothing.
