### ISSUE TITLE
thank you for your provided of the dataset

### ISSUE THREAD

**Issue by ymr1317738619** [dki-lab/Freebase-Setup#12]
In my downloading time,i want to record the things i have experienced these days.
I am a Chinese student in postgraduate sophomore year,and my tutor researched in KBQA.So i received a task to recurrence a paper about rng-kbqa.And it needs yours dataset called freebase.
You know China have network firewall. At first,I use a browser named 360 speed,and when i download about 20GB,it have been breaked by a reason i think about without breakpoint continuation.So i think about it once and once and thing about send a email to you for some help.And i found you are a professor in American,so i think you can't help me like upload the freebase to baidu cloud then i can download it with a high speed and have breakpoint continuation to protected my download.
And then,i find a word called wget,and i search it about some things.And now I am waiting for the download by wget command and  think it will success.

**Comment by ymr1317738619** [comment]
I have downloaded the freebase success**,but can you help me about install the download 53G big file?**
Now i can see the virtuoso page in port 8090 and have virtuoso.db size of 138 GB ,but i don't know how to set data to the virtuoso.

**Comment by ysu1989** [comment]
Hi, glad that you have downloaded it successfully. there's no "installation" required, apart from making sure the virtuoso tool is in place. if you are already seeing the virtuoso page, you can start writing SPARQL queries to see if you get any results, or just query the DB programatically, as instructed in the README and the provided script.
