### ISSUE TITLE
hi! I wonder is Virtuoso DB file a must for starting my virtuoso service?

### ISSUE THREAD

**Issue by Lanskttee** [dki-lab/Freebase-Setup#14]
I find it really hard to download the zip.
If I choose to download the zip from the web, the download speed is too slow, and the wget also failed and report like this:

--2023-07-06 21:49:28--  (try:20)  https://www.dropbox.com/s/q38g0fwx1a3lz8q/virtuoso_db.zip
Connecting to www.dropbox.com (www.dropbox.com)|31.13.94.7|:443... failed: Unknown error.
Connecting to www.dropbox.com (www.dropbox.com)|2001::9a55:661e|:443... failed: Unknown error.
Giving up.

**Comment by entslscheia** [comment]
Hi @Lanskttee,

Sorry about the inconvenience. This might be a network issue from China. I am thinking about providing another option that is more friendly to people in China such as BaiduYun. But looks like BaiduYun is also not very stable for non-VIP users, do you have any suggestions or other preferences?

**Comment by ysu1989** [comment]
I just uploaded the file to OneDrive: https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/su_809_osu_edu/EYRFGVk-o91Cr6sXn82EX7ABT7L0Qt4sBXydi1sgoQQA6Q?e=0jKQpu. Not sure if this might make it easier to download than Dropbox.

**Comment by JOECHEN0908** [comment]
> I just uploaded the file to OneDrive: https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/su_809_osu_edu/EYRFGVk-o91Cr6sXn82EX7ABT7L0Qt4sBXydi1sgoQQA6Q?e=0jKQpu. Not sure if this might make it easier to download than Dropbox.

Thank you! But I find that this file (29.1G) is so smaller than previous file (53G), is it correct?

**Comment by ysu1989** [comment]
oh okay I actually updated a different file to OneDrive. I think this one is the RDF triples. If you use this file, you need to bulk load it into Virtuoso, which will create the Virtuoso DB files, by following the instructions here: https://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader. I'm also trying to upload the Virtuoso DB zip file to OneDrive, but that probably will take a few days because I'm traveling.

**Comment by JOECHEN0908** [comment]
Thanks for your instruction, I will try it. If the Virtuoso DB zip file will have been uploaded, please let us know. Wish you a nice traveling! 

> oh okay I actually updated a different file to OneDrive. I think this one is the RDF triples. If you use this file, you need to bulk load it into Virtuoso, which will create the Virtuoso DB files, by following the instructions here: https://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader. I'm also trying to upload the Virtuoso DB zip file to OneDrive, but that probably will take a few days because I'm traveling.

**Comment by ysu1989** [comment]
You can try this OneDrive link for the Virtuoso DB file: https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/su_809_osu_edu/Ed0SY7sAS_ZGqNTovDYhVCcBxEmZfhL3B-chAiuoZCrpVg?e=vpHUei

**Comment by Lanskttee** [comment]
> You can try this OneDrive link for the Virtuoso DB file: https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/su_809_osu_edu/Ed0SY7sAS_ZGqNTovDYhVCcBxEmZfhL3B-chAiuoZCrpVg?e=vpHUei

Thanks for your help! That really helps me!

**Comment by Lanskttee** [comment]
> Hi @Lanskttee,
> 
> Sorry about the inconvenience. This might be a network issue from China. I am thinking about providing another option that is more friendly to people in China such as BaiduYun. But looks like BaiduYun is also not very stable for non-VIP users, do you have any suggestions or other preferences?

Thanks for your help! The OneDrive links is very nice!

**Comment by SapaePhyu** [comment]
Hi! May I know how did you decompress the downloaded file from onedrive? I got virtuoso_db.zip file after downloading but cannot decopress it either by unzip command or 7z.
