### ISSUE TITLE
How to load the preprocessed .db file?

### ISSUE THREAD

**Issue by JBoRu** [dki-lab/Freebase-Setup#3]
Hi,
   Thanks for your preprocessed file! After uncompressing the file, I get the virtuoso.db. And what should i do next? It seems not the original RDF file. Thanks for your help!

**Comment by ysu1989** [comment]
Hi, If you have followed the README and installed virtuoso, you could use the provided script `virtuoso.py` to start a triplestore service with the virtuoso.db files. See the README for more instructions.

**Comment by JBoRu** [comment]
Thanks, I have successfully run it. Is this file produced by loading the original freebase? After loading myself processed freebase and saving the checkpoint, I can also get a file like this?

**Comment by ysu1989** [comment]
yes, this is produced from the original Freebase dump, just in virtuoso DB format. You can get a file like this as well if you load the Freebase dump into Virtuoso.

**Comment by JBoRu** [comment]
Thanks for your help！
