### ISSUE TITLE
Virtuoso DB can‘t download by the dropbox web clients

### ISSUE THREAD

**Issue by wangyongshuai88** [dki-lab/Freebase-Setup#5]
Virtuoso DB file can't be downloaded 
 wget https://www.dropbox.com/s/q38g0fwx1a3lz8q/virtuoso_db.zip

I download 3 times and i got little than 10GB file  both.

So  could you please share the process script ?

**Comment by ysu1989** [comment]
That's a bit odd. Do you have enough disk space? The file is about 53 GB.

**Comment by wangyongshuai88** [comment]
Yes i have far more than 53GB space. Some people have same problem when download big file through Dropbox web client.    I have download the freebase successful.

**Comment by ZiyeLuo** [comment]
I have the same question when I download the dataset.Would you please split the data for us to download or how to post-process the freebase data downloaded from the official website？I would appreciate it if you could help us

**Comment by ysu1989** [comment]
I added the script [fix_freebase_literal_format.py](https://github.com/dki-lab/Freebase-Setup/blob/master/fix_freebase_literal_format.py) which should work for the official Freebase dump. Let me know if that doesn't work.

**Comment by wangyongshuai88** [comment]
I appreciate your support. My computer RAM is not enough to process it.   The new computer I bought yesterday is on the way. I may response you in next week.

**Comment by ysu1989** [comment]
FWIW, since the script just sequentially sweep through the data, one possibility is to split the data into several chunks to process.

**Comment by wangyongshuai88** [comment]
OK, I will try to use little part of data to walk through test.

**Comment by ZiyeLuo** [comment]
I finally solved it after a whole night of downloading, thank you！

**Comment by lirenhao1997** [comment]
> I finally solved it after a whole night of downloading, thank you！

Hi Ziye, I came across the same issue downloading this file by dropbox link. Could you tell me how you solve this problem?

**Comment by MinsGoing** [comment]
Hi Ziye, can you share the dataset with other netdisk?

**Comment by HenryCai11** [comment]
I encountered the same issue and just solved it by downloading using the dropbox desktop app, instead of using a browser.
