### ISSUE TITLE
Question about the "numeric_properties.txt"

### ISSUE THREAD

**Issue by iDylanCui** [dki-lab/Freebase-Setup#6]
Thanks for sharing the codes! I have one question.

In "fix_freebase_literal_format.py", I observe that "numeric_properties.txt" is opened, but I could not find the file in this repository. Could you please upload this file, or somewhere I can get this file?

Thank you very much!
I am looking forward to receiving your comments.

**Comment by JimXiongGM** [comment]
This may be helpful: https://github.com/dki-lab/GrailQA/blob/0de52d18463e986047165dfeb085272513cad1ad/utils/search_over_graphs.py#L38

**Comment by ysu1989** [comment]
just uploaded the file. It should be the file that I used for the processing but I'm not exactly sure, so feel free to let me know if that doesn't work.

**Comment by iDylanCui** [comment]
Thanks very much!

**Comment by ysu1989** [comment]
closing for now since this seems solved.
