### ISSUE TITLE
Running Virtuoso on Server

### ISSUE THREAD

**Issue by ediyh** [dki-lab/Freebase-Setup#8]
Hi,

Thanks for the repo. I followed the instructions in README, downloaded the virtuoso_db and Virtuoso, and ran `python3 virtuoso.py start 3001 -d virtuoso_db`.

It launched successfully, the information shows `==== Starting Virtuoso server for /usr/data/virtuoso_db on port 3001...`. However, when I access the server on port 3001, the webpage shows `Error HTTP/1.1 404 File not found
The requested URL was not found    URI  = '/'`. 

May I know how I may fix this? Thanks!!

**Comment by ysu1989** [comment]
is your downloaded db file actually located at /usr/data/virtuoso_db?

**Comment by ediyh** [comment]
Yes, under that folder I have files:
```
virtuoso.db  virtuoso.ini  virtuoso.lck  virtuoso.log  virtuoso.pxa  virtuoso-temp.db  virtuoso.trx
```

**Comment by ysu1989** [comment]
then it may be worth checking whether the virtuoso db was actually successfully started and checking the log file

**Comment by ediyh** [comment]
Here's the content the log file
```
12:14:21 Roll forward complete
12:14:25 Checkpoint started
12:14:26 Checkpoint finished, log reused
12:14:26 HTTP server online at 3001
12:14:26 Server online at 13001 (pid 5654)
```
Not sure why the last line shows server online at 13001. However I tried both the port 3001 and 13001, neither works. Really appreciate any pointers!

**Comment by ysu1989** [comment]
it looks like the server was successfully started (you may use `top` to double check if it's still running). As noted in the provided script, the services runs on two ports, 3001 for HTTP service and 13001 for `isql` service. Maybe your server has some firewall settings that disables external HTTP access. Just a guess.

**Comment by ediyh** [comment]
hmm.. this is very weird because tensorboard / jupyter notebook works fine on the server.
