### ISSUE TITLE
Problems about the server

### ISSUE THREAD

**Issue by luoxindi** [dki-lab/Freebase-Setup#9]
Hello, I followed the tutorial totally, and started the server with port 3001. However, when I opened the url, what appeared was the Baidu search interface. Is this normal？

**Comment by ysu1989** [comment]
that shouldn't be the case so it's not normal. You should see the Sparql query editor interface which looks like this: https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fmax%2F1200%2F1*Pj11IUX0MfGJGSBtmIZBRw.png&imgrefurl=https%3A%2F%2Fmedium.com%2Fvirtuoso-blog%2Fgenerate-sparql-query-compilation-report-from-a-virtuoso-sparql-endpoint-5a54f73ebdd0&tbnid=MuZBmuPR7Pt9VM&vet=12ahUKEwj4sOSUwqn7AhU-QUIHHVujAV4QMygCegUIARC3AQ..i&docid=dGtwOJKoZQHy-M&w=1200&h=840&q=virtuoso%20sparql%20endpoint&ved=2ahUKEwj4sOSUwqn7AhU-QUIHHVujAV4QMygCegUIARC3AQ
